[workspace]
members = ["initial-contract", "enum-upgraded-contract","migration-upgraded-contract", "upgradable-contract"]

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true